from collections.abc import AsyncGenerator

import asyncpg

from core.config import settings


pool: asyncpg.Pool | None = None


SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre TEXT NOT NULL UNIQUE,
    categorie TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    annee INTEGER NOT NULL,
    studio TEXT NOT NULL,
    plateforme TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_items_categorie ON items(categorie);

CREATE TABLE IF NOT EXISTS collection_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    statut TEXT NOT NULL DEFAULT 'a_decouvrir'
        CHECK (statut IN ('a_decouvrir', 'en_cours', 'termine')),
    note INTEGER CHECK (note BETWEEN 1 AND 5),
    commentaire TEXT,
    date_ajout TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_item UNIQUE (user_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_entries_user ON collection_entries(user_id);
"""


async def init_db() -> None:
    global pool

    pool = await asyncpg.create_pool(
        dsn=settings.DATABASE_URL,
        min_size=1,
        max_size=5,
    )

    try:
        async with pool.acquire() as conn:
            await conn.execute(SCHEMA)
    except Exception:
        await pool.close()
        pool = None
        raise


async def close_db() -> None:
    global pool

    if pool is not None:
        await pool.close()
        pool = None


def get_pool() -> asyncpg.Pool:
    if pool is None:
        raise RuntimeError("La base de données n'est pas initialisée")

    return pool


async def get_session() -> AsyncGenerator[asyncpg.Connection, None]:
    async with get_pool().acquire() as conn:
        yield conn